# Generated by Django 6.0 on 2025-12-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_borrow_is_returned_alter_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Biography', 'Biography'), ('Children', 'Children'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery')], max_length=100),
        ),
    ]
